#!/usr/bin/env zsh

. ~/.dotfiles/environment.zsh

# oh-my-zsh options
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  ruby
  github
  httpie
  zsh-syntax-highlighting
  npm
  yarn
)

if [ -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] ; then
  plugins+=( zsh-autosuggestions )
fi

source $ZSH/oh-my-zsh.sh

# User configuration

if which chezmoi>/dev/null; then
  export DOTFILES=~/.dotfiles
  eval $(chezmoi completion zsh)
fi

alias cm=chezmoi
alias cma="chezmoi apply && source ~/.zshrc"

cow () {
  fortune /Users/sophie/Code/test/lgtm | cowsay -f $(ls /opt/homebrew/opt/cowsay/share/cows | shuf -n1)
}

if which code >/dev/null; then
  export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
fi

#-tns-completion-
if [ -f ~/.tnsrc ]; then
  source ~/.tnsrc
fi

if [ -d ~/.fastlane/bin ] ; then
  export PATH="~/.fastlane/bin:$PATH"
fi

for f in ~/.dotfiles/**/config.zsh; do
  source $f
done

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/Users/sophie/Code/test/LGTM:$PATH"

source ~/.dotfiles/completions.zsh

eval "$(starship init zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
